### ISSUE TITLE
人気記事ランキングを横並びから縦並びに表示させる

### ISSUE THREAD

**Issue by taichi-kobaya** [taichi-kobaya/wordpress_tutorial#1]

**Comment by taichi-kobaya** [comment]
人気記事の縦並び、横並びはどこで制御されているんでしょうか？

`wordpress/wp-content/themes/xeory_extension/front-page.php`
```
<h2><i class="fa fa-flag"></i> 人気のある記事</h2>
<div class="wrap">
  <div class="front-loop-cont">
<?php
      $i = 1;
      if ( have_posts() ) :
        // wp_reset_query();
        $args=array(
            'meta_query'=>
            array(
              array(  'key'=>'bzb_show_toppage_flag',
                         'compare' => 'NOT EXISTS'
              ),
              array(  'key'=>'bzb_show_toppage_flag',
                        'value'=>'none',
                        'compare'=>'!='
              ),
             'relation'=>'OR'
          ),
            'showposts'=>5,
            'meta_key'=>'views',
            'orderby'=>'meta_value_num',
            'order'=>'DESC'
          );
        query_posts($args);
        // query_posts('showposts=5&meta_key=views&orderby=meta_value_num&order=DESC');
        while ( have_posts() ) : the_post();
        $cf = get_post_meta($post->ID);
        $rank_class = 'popular_post_box rank-'.$i;
        // print_r($cf);
?>
```

上記'showposts'=>5の数字を変更すると表示される記事数が変わるのでこのあたりかな？
と思いながら調べていますが、縦並び・横並びはどこを修正すれば良いかヒント頂きたいです。

因みにプラグインなしで人気記事を表示する方法は出てきましたが、
元のテーマの横並び表示を縦並び表示にする方法は見つけられませんでした。

https://manablog.org/wordpress-popular-posts-without-plugin/

**Comment by taichi-kobaya** [comment]
@Takuma-Ikeda さん

人気記事の縦並び、横並びはどこで制御されているんでしょうか？

`wordpress/wp-content/themes/xeory_extension/front-page.php`

```
<h2><i class="fa fa-flag"></i> 人気のある記事</h2>
<div class="wrap">
  <div class="front-loop-cont">
<?php
      $i = 1;
      if ( have_posts() ) :
        // wp_reset_query();
        $args=array(
            'meta_query'=>
            array(
              array(  'key'=>'bzb_show_toppage_flag',
                         'compare' => 'NOT EXISTS'
              ),
              array(  'key'=>'bzb_show_toppage_flag',
                        'value'=>'none',
                        'compare'=>'!='
              ),
             'relation'=>'OR'
          ),
            'showposts'=>5,
            'meta_key'=>'views',
            'orderby'=>'meta_value_num',
            'order'=>'DESC'
          );
        query_posts($args);
        // query_posts('showposts=5&meta_key=views&orderby=meta_value_num&order=DESC');
        while ( have_posts() ) : the_post();
        $cf = get_post_meta($post->ID);
        $rank_class = 'popular_post_box rank-'.$i;
        // print_r($cf);
?>
```

上記'showposts'=>5の数字を変更すると表示される記事数が変わるのでこのあたりかな？
と思いながら調べていますが、縦並び・横並びはどこを修正すれば良いかヒント頂きたいです。

因みにプラグインなしで人気記事を表示する方法は出てきましたが、
元のテーマの横並び表示を縦並び表示にする方法は見つけられませんでした。

https://manablog.org/wordpress-popular-posts-without-plugin/

**Comment by iQeda** [comment]
@taichi-kobaya CC: @katakabe 
デベロッパーツールでランキングの箇所を選択して、その HTML/CSS がどうなっているのか確認すればよいのでは？
「縦並びか横並びか」は単なる HTML/CSS の見せ方の問題です。
貼っている PHP のソースコードはランキングのデータ取得です。ランキングの HTML 内でここの変数を埋め込んでいるはずです。

また Slack にも書きましたが、`wordpress/wp-content/themes/xeory_extension` は親テーマなので、ここイジると混乱しかねないです。まず子テーマを作成してください。

また CSS を使うということは、SCSS を導入している必要があります。こちらの準備はできていますか？その Issue はありますか？タスクの優先順位をまず考えましょう！

**Comment by taichi-kobaya** [comment]
SCSSの準備はまだ出来ていませんでした。
Issue作成し、優先して進めたいと思います。

子テーマについてはローカルで作成し、まだプッシュしていません。
この方法で良いのか確認してからプッシュしようと思っていました。
これからプッシュしますので間違っていたらご指摘いただければ幸いです。

**Comment by iQeda** [comment]
@taichi-kobaya 
(もしかして片伯部さんは小林さんが子テーマ作っていることを知っているのかもしれないけど)
「Issue が立っていない (Asignee が不明) 、push もされていない」状況だと池田や片伯部さんもローカルで子テーマ作ってプッシュしまう可能性があるので、早々に対応したほうがよいかと！
今はまだ 3 人だからよいのですが、大人数で開発するときはこういった連携漏れが致命傷になりかねないので注意が必要です！

**Comment by taichi-kobaya** [comment]
issue対応しましたのでクローズします。
